apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: { name: kube-prom-stack, namespace: flux-system }
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=61.0.0"
      sourceRef: { kind: HelmRepository, name: prometheus-community, namespace: flux-system }
  values:
    prometheus:
      service:
        type: NodePort
        nodePort: 30090
    grafana:
      service:
        type: NodePort
        nodePort: 30030